### ISSUE TITLE
find method in diskdb does not return correct  result when query contains more than one property

### ISSUE THREAD

**Issue by kiranps** [arvindr21/diskDB#10]
I saved two objects like this

    db.sam.save({name: "kiran",phno:"123"});
    db.sam.save({name: "kiran",phno:"123456"});

and i wrote a query to find obj with {name: "kiran",phno:"123"}

    db.sam.find({name: "kiran",phno:"123"});

the result that i get is

[ {name: "kiran",
phno:"123",
_id: "997044f2d16d440aa3b6588d4d228bea"},
{name: "kiran",
phno:"123456",
_id: "26b670304d844d9b957abf367e47f153"}
]

but the answere is supposed to be

[ {name: "kiran",
phno:"123",
_id: "997044f2d16d440aa3b6588d4d228bea"}
]

**Comment by kiranps** [comment]
i have fixed this problem by using underscorejs

i replaced

    return searcher.findAllInObject(collection, query, true);

by

   return _.where(collection, query)

do you want to merge it with main repository

**Comment by arvindr21** [comment]
Thanks @kiranps. But I am not planning to use `_`. If you have a solution without `_`, feel free to submit a PR. Thanks.

**Comment by arvindr21** [comment]
Fixed with https://github.com/arvindr21/diskDB/pull/17
