### ISSUE TITLE
Joining two collections

### ISSUE THREAD

**Issue by mpsbhat** [arvindr21/diskDB#13]
Is it possible to join two collections say user and user details with a common id something similar to sql join.

**Comment by arvindr21** [comment]
No, not with DiskDB. But you can use Mongoose with MongoDB for the same.

**Comment by mpsbhat** [comment]
Thank you. I have tried with mongoose as,
 `var mongoose = require('./mongoose');
                            mongoose.connect('mongodb://127.0.0.1:27017/myDBName');
                            var db = mongoose.connection;
                            db.on('error', console.error.bind(console, 'connection error:'));
                            db.once('open', function () {
                                alert();
                            });`

where mongoose folder located at the root folder of my project, but it given the following error.

`message: "connect ECONNREFUSED 127.0.0.1:27017"
name: "MongoError"`

**Comment by arvindr21** [comment]
@mpsbhat The simplest solution is to write two queries. And join them manually. Ignore my mongoose comment.

**Comment by patchfx** [comment]
@mpsbhat Assuming this answered your question.

**Comment by mpsbhat** [comment]
Thank you. Myself used with `underscorejs` to solve the issue.
