### ISSUE TITLE
Find the collections with two conditions

### ISSUE THREAD

**Issue by mpsbhat** [arvindr21/diskDB#14]
How to find the collections with two conditions something equivalent to sql and conditions (`where Userid=12 and updated=0`).

I tried with `db.settings.find({"Userid": 12, "updated": 0})` but it returns all the data.

**Comment by bteixeira** [comment]
+1

I just started using this package and it seems cool, but this is a total deal breaker. I'm trying to update a collection in which the "primary key" is made of two different fields, and the "upsert" operation basically thinks all my records match.

**Comment by bteixeira** [comment]
I think the easiest and best way to approach this would be to allow the `query` parameter to be a filter function, which returns truthy or falsy depending on whether a record should be updated or not.

@arvindr21 would you be willing to merge a PR with the above?

**Comment by arvindr21** [comment]
@bteixeira Sure, please send it across with test cases. I will consider it.

**Comment by mpsbhat** [comment]
Thank you for the consideration. Myself managed with `underscore.js` filter function for filtering with multiple condition but it is appreciated if diskDB itself have that functionality in future.

**Comment by arvindr21** [comment]
Fixed with https://github.com/arvindr21/diskDB/pull/17
