### ISSUE TITLE
How to use multiple condition in find?

### ISSUE THREAD

**Issue by BrstDev123** [arvindr21/diskDB#33]
In users.json data is 
`[{"email":"noname@email.com","password":"123","status":"1","_id":"e39a62a9c7b94d76892f9c3bdfa22715"}]`

I am using it as follows: 

```
        db.loadCollections(['users']);

        var preCheck = db.users.find({"email" : req.body.email,"password" : req.body.password});

        if(preCheck !== undefined){
           
            if( (preCheck.email == req.body.email) && (preCheck.password == req.body.password) ){ 
                //logged in
                
                req.session.email = req.body.email;
                req.session.userId = preCheck._id;
                req.flash('success','Successful Login');
                res.redirect('/option');
            }
            else{
               
                req.flash('error','Email Id or Password is Incorrect');
                res.redirect('/login');
            }
        }
```

But it returns invalid login always.

**Comment by staticmukesh** [comment]
I think, syntax is correct for multiple conditions in search.

Try `console.log(preCheck)`. You will find it to be `array` of matched results, not single object, that's why `if` condition is failing. 

Use `findOne` instead.

**Comment by patchfx** [comment]
@BrstDev123 You are getting back an array as @staticmukesh says, whereas it appears you are expecting a hash. You could either grab the first result in the array - though that's a little brittle, or use `findOne`. 

`var preCheck = db.users.findOne({"email" : req.body.email,"password" : req.body.password});`

**Comment by patchfx** [comment]
@BrstDev123 I'm closing this issue, guessing it's solved for you now?

**Comment by BrstDev123** [comment]
Well issue was not resolved , But I have replaced diskdb with sqlite3.. If you wants then close.
Thank you!
