### ISSUE TITLE
Let's get this Async started

### ISSUE THREAD

**Issue by oronbz** [arvindr21/diskDB#6]
So, to continue to our comments on "The Jackal of Javascript Blog" (http://thejackalofjavascript.com/ionic-twilio-and-node-scheduler-part-1/), let's start and plan our naming convention for the async mehtods.

I say, to not make a braking change keep the current methods as is,
Give them new aliases like: "newMethodNameSync()"
and add the async version without prefix: "newMethodName()" to keep it in the node convention way.

We just need to think about new method names for each method.

**Comment by Stefdv** [comment]
I love diskDb for development, and some small applications, but is there a async version yet ( with Promise ) ?

**Comment by arvindr21** [comment]
As of now, No. But I am open for a PR.

**Comment by bcolucci** [comment]
Could someone check my PR with the es6 stuff?
I'll be able after this PR to make the async version in like... few hours :)

**Comment by patchfx** [comment]
@bcolucci I will take a look. The change is quite large so will need some time to review it. Will get back to you shortly.

Appreciate you tackling this feature, thanks!

**Comment by staticmukesh** [comment]
I guess, nobody is working on `async` part of library. So, I have started working on it with callback way. 

For now, I am leaving `sync` functions names as it is, and appending `Async` on asynchronous methods. 

We can decide about naming later :)

**Comment by patchfx** [comment]
@staticmukesh There is a form created by @bcolucci which we are considering for merge. The implementation I believe is complete. We are currently doing some testing on it. See PR #30

**Comment by staticmukesh** [comment]
I am kind of done with the Async feature. So, should I wait for PR 30 to merge ?

**Comment by patchfx** [comment]
Yes - although currently there are some conflicts in the PR.

@bcolucci are you able to pull in the latest code and resolve the conflicts with your branch?

**Comment by bcolucci** [comment]
No problem. I check that asap.

**Comment by bcolucci** [comment]
@patchfx sorry for the delay, it's done :)
I'll propose some ES6 improvements soon in an other PR.

**Comment by staticmukesh** [comment]
Please merge that PR, then I can make `async` changes.

**Comment by patchfx** [comment]
@bcolucci @staticmukesh This has been merged into master now.
