### ISSUE TITLE
Insert new item of child array?

### ISSUE THREAD

**Issue by vnaking** [arvindr21/diskDB#8]
with your [example db](https://github.com/arvindr21/diskDB/blob/master/examples/db/articles.json) How can I insert a new comment to an article?

**Comment by vnaking** [comment]
if DB articleComments is 
{
    title: 'diskDB rocks',
    published: '2 days ago',
    comments: [{
        name: 'a user',
        comment: 'this is cool',
        rating: 2
    }, {
        name: 'b user',
        comment: 'this is ratchet',
        rating: 3
    }, {
        name: 'c user',
        comment: 'this is awesome',
        rating: 2
    }]
}
and i got new comment from 'd user', what is the query to add new comment to articleComments ?

**Comment by arvindr21** [comment]
AFAIK there is no straightforward way. You need to fetch the collection, add the new comment and then update the DB

```js
var db = require('diskdb');
db = db.connect('db', ['articles']);

var articleComments = {
    title: 'diskDB rocks',
    published: '2 days ago',
    comments: [{
        name: 'a user',
        comment: 'this is cool',
        rating: 2
    }, {
        name: 'b user',
        comment: 'this is ratchet',
        rating: 3
    }, {
        name: 'c user',
        comment: 'this is awesome',
        rating: 2
    }]
}

var savedArticle = db.articles.save(articleComments);
console.log("savedArticle", '\n', savedArticle);

// Data to save
var newComment = {
        name: 'd user',
        comment: 'this is a new comment',
        rating: 5
    };

var dbArticle = db.articles.findOne({ title: 'diskDB rocks'});
dbArticle.comments.push(newComment);

var reSavedArticle = db.articles.update({ 
  title: 'diskDB rocks'
  },
  dbArticle, {
  multi: false,
  upsert: false
});

console.log("reSavedArticle", '\n',  db.articles.findOne({ title: 'diskDB rocks'}));
```

Checkout this Runnable :  http://runnable.com/VKVAcfCJhE4mSpYL/diskdb-issue-8-for-node-js for a live preview. Run `node index.js` in the terminal at the bottom.

**Comment by vnaking** [comment]
thanks @arvindr21  it helped me!

**Comment by arvindr21** [comment]
:+1:

**Comment by vnaking** [comment]
but it should have a straightforward way to do that.

**Comment by arvindr21** [comment]
The problem is that we do not know the nesting of the child object. In the above the example, `comments` is an `[]` but in some other scenario it can be an object and we may need to add a new property to it like 

```js
var articleComments = {
    title: 'diskDB rocks',
    published: '2 days ago',
    comment: {
        name: 'a user',
        comment: 'this is cool',
        rating: 2,
        date : now
    }
}
```

This approach will keep the parser light-weight.
